backend:
  name: github
  repo: dev-ahmedhany/intro-to-web-dev
  branch: master

media_folder: static/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "lessons"
    label: "Lessons"
    folder: "lessons/"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{path}}"
    identifier_field: path
    summary: "{{title}}"
    sortable_fields: ['order']
    fields:
      - label: "Path"
        name: "path"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Order"
        name: "order"
        widget: "number"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "tweets"
    label: "Tweets"
    delete: false
    editor:
      preview: false
    files:
      - name: "tweets"
        label: "Tweets"
        file: "content/tweets.yml"
        description: "Tweets Ids"
        fields:
          - name: tweets
            label: Tweets
            label_singular: "Tweet"
            description: "List of Tweets"
            widget: list
            field:
              label: "ID"
              name: "id"
              widget: "string"
              hint: "the tweet id appears in url"